labels:
  "test": "true"

namespace: test-namespace

roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: foo
  kind: Role

subjects:
  - kind: User
    name: bar
    apiGroup: rbac.authorization.k8s.io
