apiVersion: v2
appVersion: "v1.0.0"
home: https://github.com/ameijer/k8s-as-helm
description: Helm Chart representing a single Secret Kubernetes API object
name: secret
version: 1.0.0
maintainers:
  - name: ameijer
    url: https://github.com/ameijer
keywords:
- secret
- api
- primitives
