labels:
  "test": "true"

containers:
  testcontainer1:
    image: busybox
    extraSettings:
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          echo "hello world, running the job!"
restartPolicy: Never
extraSettings:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

backoffLimit: 7
completions: 7
parallelism: 2
activeDeadlineSeconds: 601
ttlSecondsAfterFinished: 60

podAnnotations:
  test: true
podLabels:
  test: true
