labels:
  "test": "true"

egressRules:
  - ports:
      - port: 2
        protocol: UDP
  - ports:
      - port: 54
    selectors:
      - podSelector:
          matchLabels:
            app: test
            release: test
podSelector:
  matchLabels:
    app: testApp

ingressRules:
  - selectors:
      - podSelector:
          matchLabels:
            app: testApp
            release: testRelease
      - namespaceSelector:
          matchLabels:
            testnamespace: "true"
    ports:
      - protocol: TCP
        port: 4
