apiVersion: v2
appVersion: 1.0.0
home: https://github.com/ameijer/k8s-as-helm
description: Library chart backing portions of the k8s-as-helm project
name: lib-k8s-as-helm
version: 1.1.0
icon: https://ameijer.github.io/k8s-as-helm/icon.png
type: library
maintainers:
  - name: ameijer
    url: https://github.com/ameijer
keywords:
- library
- k8s-as-helm
- api
- primitives
