apiVersion: {{ template "apiVersion" . }}
kind: Secret
metadata:
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ template "secret.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
  name: {{ template "secret.name" . }}
data:
{{-  range $secretKey, $secretValue := .Values.secretData }}
  {{ $secretKey }}: {{ $secretValue | b64enc | quote }}
{{- end }}
{{-  range $secretKey, $secretValueEncoded := .Values.secretDataEncoded }}
  {{ $secretKey }}: {{ $secretValueEncoded }}
{{- end }}
type: {{ .Values.type }}
