apiVersion: v2
appVersion: "v1.0.0"
home: https://github.com/ameijer/k8s-as-helm
description: Helm Chart representing a single Job Kubernetes API object
name: job
version: 1.0.0
icon: https://ameijer.github.io/k8s-as-helm/icon.png
dependencies:
- name: lib-k8s-as-helm
  version: 1.2.0
  repository: https://ameijer.github.io/k8s-as-helm
maintainers:
  - name: ameijer
    url: https://github.com/ameijer
keywords:
- job
- api
- primitives
